// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadVideo(arg1:string,arg2:string):Promise<string>;

export function GetVideoAuthor(arg1:string):Promise<string>;

export function GetVideoTitle(arg1:string):Promise<string>;

export function WriteALogFile(arg1:string):Promise<void>;
