// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadVideo(arg1, arg2) {
  return window['go']['main']['App']['DownloadVideo'](arg1, arg2);
}

export function GetVideoAuthor(arg1) {
  return window['go']['main']['App']['GetVideoAuthor'](arg1);
}

export function GetVideoTitle(arg1) {
  return window['go']['main']['App']['GetVideoTitle'](arg1);
}

export function WriteALogFile(arg1) {
  return window['go']['main']['App']['WriteALogFile'](arg1);
}
